# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Learning Resources', url: 'resources'}
- {name: 'Goals',            url: 'goals'}
- {name: 'Documentation',      url: 'documentation'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/topofthehil'}
- {icon: 'envelope', link:   'mailto:hi@jonathanhilgart.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
